config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  root to: 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html> <html>
<head>
  <title>ShopAndJoy</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body class="<%= controller.controller_name %>">
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"> <h1><a href="<%= store_url %>">Главная</a></h1> </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon">
      <a href="#"><span>Menu</span></a>
    </li> </ul> <section class="top-bar-section">
  <!-- Right Nav Section -->
  <ul class="right">
    <li class="active"><a href="<%= login_url %>">Администратор</a> </li>
    <li class="active"><a href="#">Right Button Active</a></li>
    <li class="has-dropdown"> <a href="#">Right Button Dropdown</a> <ul class="dropdown">
      <li><a href="#">First link in dropdown</a></li>

    </ul> </li> </ul>

  <!-- Left Nav Section -->

  <ul class="left">
    <li><a href="#">Left Nav Button</a></li>
    <li class="has-form"> <div class="row collapse"> <div class="large-8 small-9 columns"> <input type="text" placeholder="Найти товар"> </div> <div class="large-4 small-3 columns"> <a href="#" class="alert button expand">Найти</a> </div> </div> </li>
  </ul>
</section>
</nav>
<div id="columns">
  <div id="side">
  
        <div id="cart">
      <% if @cart %>
          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
          <% end %>
      <% end %>
          </div>

    <% if session[:user_id] %>
        <br />
        <%= link_to 'Orders', orders_path %><br />
        <%= link_to 'Products', products_path %><br />
        <br />
        <%= button_to 'Выйти', logout_path, method: :delete, class: 'button', class: 'button' %>
    <% end %>
  </div>

  <div id="main">
    <%= yield %>
  </div>
</div>
</body>
</html>